server:
  port: 9527
eureka:
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: microservicecloud-zuul-gateway
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept
  prefix: /sz

info:
  app.name: microservicecloud-zuul